version: '3.1'

services:
  nginx:
    container_name: web_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - internal

  php-fpm:
    container_name: web_phpfpm
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./app:/var/www
      - ./docker/php-fpm/logs:/var/log/php
    depends_on:
      - db
    networks:
      - internal

  db:
    container_name: web_db
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111
    volumes: 
      - ./docker/mariadb/data:/var/lib/mysql

  phpmyadmin:
    container_name: web_myadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

networks:
  internal:
    driver: bridge