CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT NOT NULL,
  date TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 'Sales', '10.03.22');
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 'Sales','10');
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', 'Sales', '15');
INSERT INTO EMPLOYEE VALUES (0004, 'Ava', 'Sales', '10');

-- fetch 
SELECT * FROM EMPLOYEE WHERE dept = 'Sales';
SELECT * FROM EMPLOYEE WHERE date = '10';
SELECT * FROM EMPLOYEE WHERE name = 'Ava';
SELECT * FROM EMPLOYEE WHERE empId  = '0001';